//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tnt_deploy_brush_car.proto
namespace tnt_deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BRUSH_CAR")]
  public partial class BRUSH_CAR : global::ProtoBuf.IExtensible
  {
    public BRUSH_CAR() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<tnt_deploy.BRUSH_CAR.car_info> _car_list = new global::System.Collections.Generic.List<tnt_deploy.BRUSH_CAR.car_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"car_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tnt_deploy.BRUSH_CAR.car_info> car_list
    {
      get { return _car_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"car_info")]
  public partial class car_info : global::ProtoBuf.IExtensible
  {
    public car_info() {}
    
    private uint _car_id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"car_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint car_id
    {
      get { return _car_id; }
      set { _car_id = value; }
    }
    private uint _pos_id = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint pos_id
    {
      get { return _pos_id; }
      set { _pos_id = value; }
    }
    private uint _velocity_id = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"velocity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint velocity_id
    {
      get { return _velocity_id; }
      set { _velocity_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BRUSH_CAR_ARRAY")]
  public partial class BRUSH_CAR_ARRAY : global::ProtoBuf.IExtensible
  {
    public BRUSH_CAR_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<tnt_deploy.BRUSH_CAR> _items = new global::System.Collections.Generic.List<tnt_deploy.BRUSH_CAR>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tnt_deploy.BRUSH_CAR> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}