//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tnt_deploy_car_velocity.proto
namespace tnt_deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAR_VELOCITY")]
  public partial class CAR_VELOCITY : global::ProtoBuf.IExtensible
  {
    public CAR_VELOCITY() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private tnt_deploy.CAR_VELOCITY.velocity _car_velocity = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"car_velocity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tnt_deploy.CAR_VELOCITY.velocity car_velocity
    {
      get { return _car_velocity; }
      set { _car_velocity = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"velocity")]
  public partial class velocity : global::ProtoBuf.IExtensible
  {
    public velocity() {}
    
    private float _x = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAR_VELOCITY_ARRAY")]
  public partial class CAR_VELOCITY_ARRAY : global::ProtoBuf.IExtensible
  {
    public CAR_VELOCITY_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<tnt_deploy.CAR_VELOCITY> _items = new global::System.Collections.Generic.List<tnt_deploy.CAR_VELOCITY>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tnt_deploy.CAR_VELOCITY> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}