# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tnt_deploy_skill.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tnt_deploy_skill.proto',
  package='tnt_deploy',
  serialized_pb='\n\x16tnt_deploy_skill.proto\x12\ntnt_deploy\"\x80\x03\n\x05SKILL\x12\r\n\x02id\x18\x01 \x02(\r:\x01\x30\x12\x0e\n\x04name\x18\x02 \x01(\t:\x00\x12\x12\n\x08template\x18\x03 \x01(\t:\x00\x12\x11\n\x07respath\x18\x04 \x01(\t:\x00\x12\x17\n\rui_skill_icon\x18\x05 \x01(\t:\x00\x12\x11\n\x07hit_efx\x18\x06 \x01(\t:\x00\x12\x0f\n\x04type\x18\x07 \x01(\r:\x01\x30\x12\x0e\n\x03\x64ir\x18\x08 \x01(\r:\x01\x30\x12\x17\n\x0c\x61void_method\x18\t \x01(\r:\x01\x30\x12\x30\n\x0c\x65\x66x_velocity\x18\n \x01(\x0b\x32\x1a.tnt_deploy.SKILL.velocity\x12\x13\n\x08\x64uration\x18\x0b \x01(\x02:\x01\x30\x12\x16\n\x0bspeed_scale\x18\x0c \x01(\x02:\x01\x30\x12\x13\n\x08\x63hg_time\x18\r \x01(\x02:\x01\x30\x12\x18\n\rcontinue_time\x18\x0e \x01(\x02:\x01\x30\x12\x15\n\nreset_time\x18\x0f \x01(\x02:\x01\x30\x1a&\n\x08velocity\x12\x0c\n\x01x\x18\x01 \x01(\x02:\x01\x30\x12\x0c\n\x01y\x18\x02 \x01(\x02:\x01\x30\"/\n\x0bSKILL_ARRAY\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.tnt_deploy.SKILL')




_SKILL_VELOCITY = _descriptor.Descriptor(
  name='velocity',
  full_name='tnt_deploy.SKILL.velocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='tnt_deploy.SKILL.velocity.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='tnt_deploy.SKILL.velocity.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=385,
  serialized_end=423,
)

_SKILL = _descriptor.Descriptor(
  name='SKILL',
  full_name='tnt_deploy.SKILL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tnt_deploy.SKILL.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='tnt_deploy.SKILL.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='template', full_name='tnt_deploy.SKILL.template', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='respath', full_name='tnt_deploy.SKILL.respath', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ui_skill_icon', full_name='tnt_deploy.SKILL.ui_skill_icon', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hit_efx', full_name='tnt_deploy.SKILL.hit_efx', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tnt_deploy.SKILL.type', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dir', full_name='tnt_deploy.SKILL.dir', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avoid_method', full_name='tnt_deploy.SKILL.avoid_method', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='efx_velocity', full_name='tnt_deploy.SKILL.efx_velocity', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='tnt_deploy.SKILL.duration', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed_scale', full_name='tnt_deploy.SKILL.speed_scale', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chg_time', full_name='tnt_deploy.SKILL.chg_time', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='continue_time', full_name='tnt_deploy.SKILL.continue_time', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reset_time', full_name='tnt_deploy.SKILL.reset_time', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SKILL_VELOCITY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=423,
)


_SKILL_ARRAY = _descriptor.Descriptor(
  name='SKILL_ARRAY',
  full_name='tnt_deploy.SKILL_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='tnt_deploy.SKILL_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=425,
  serialized_end=472,
)

_SKILL_VELOCITY.containing_type = _SKILL;
_SKILL.fields_by_name['efx_velocity'].message_type = _SKILL_VELOCITY
_SKILL_ARRAY.fields_by_name['items'].message_type = _SKILL
DESCRIPTOR.message_types_by_name['SKILL'] = _SKILL
DESCRIPTOR.message_types_by_name['SKILL_ARRAY'] = _SKILL_ARRAY

class SKILL(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class velocity(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SKILL_VELOCITY

    # @@protoc_insertion_point(class_scope:tnt_deploy.SKILL.velocity)
  DESCRIPTOR = _SKILL

  # @@protoc_insertion_point(class_scope:tnt_deploy.SKILL)

class SKILL_ARRAY(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SKILL_ARRAY

  # @@protoc_insertion_point(class_scope:tnt_deploy.SKILL_ARRAY)


# @@protoc_insertion_point(module_scope)
